<?php if(!DEFINED('BASEPATH')) {Die('No Script Access!');}
	//Paths for directories
	DEFINE('APP_PATH', BASEPATH . '/admin/app');
	DEFINE('SERVERPATH', 'http://' . $_SERVER['HTTP_HOST']);
	DEFINE('ROOT_PATH', SERVERPATH . '/admin');

	DEFINE('GROUPS', APP_PATH . '/groups');
	DEFINE('VIEWS', APP_PATH .'/views');
	DEFINE('MODELS', APP_PATH . '/models');
	DEFINE('CONTROLLERS', APP_PATH . '/controllers');
	DEFINE('UPLOADS', APP_PATH . '/uploads');



	//Database Credentials
	DEFINE('DATABASE_SERVER', 'mysql');
	DEFINE('DATABASE_NAME', 'apollo-db');
	DEFINE('DATABASE_USER', 'root');
	DEFINE('DATABASE_PASSWORD', 'root');

	DEFINE('DATABASE_TABLE_PREFIX', 'ap_');

	DEFINE('TYPE_TABLE_PREFIX', DATABASE_TABLE_PREFIX . 'type_');

	DEFINE('GROUPS_TABLE', DATABASE_TABLE_PREFIX . 'groups');
	DEFINE('CONTENT_TABLE', DATABASE_TABLE_PREFIX . 'content');
	DEFINE('DATA_TABLE', DATABASE_TABLE_PREFIX . 'data');
	DEFINE('TYPES_TABLE', DATABASE_TABLE_PREFIX . 'types');
	DEFINE('MEDIA_TABLE', DATABASE_TABLE_PREFIX . 'media_library');

	DEFINE('COMPOUND_TYPE_FIELDS_TABLE', DATABASE_TABLE_PREFIX . 'compound_type_fields');

	//Data Management
	DEFINE('DATA_GUID_PREFIX', 'DATA');
